"""
Django settings for mingdyn project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from dotenv import load_dotenv
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@bprd)j9_+brp01g(h5z$)h2nl3$q*clkhu0j=!ti8y8)(cqo0'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', SECRET_KEY)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

# Allow your domain and proxy headers
ALLOWED_HOSTS = ["ming-group.de", "www.ming-group.de"]
CSRF_TRUSTED_ORIGINS = ["https://ming-group.de", "https://www.ming-group.de"]

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mingsite',
    'locations',
    'menus',
    'gallery',
    'reservations',
    'testimonials',
    'legal',
    'core_settings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mingdyn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mingdyn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

load_dotenv(BASE_DIR / '.env')

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "mingdyn"),
        "USER": os.getenv("DB_USER", "mingdyn"),
        "PASSWORD": os.getenv("DB_PASSWORD", "mingdyn"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,   # keep connections open for 60s
        "OPTIONS": {},        # add pg options here if needed
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/Berlin"
USE_TZ = True
USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']

STATICFILES_DIRS = [BASE_DIR / 'static']  # where we keep source static files

DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

FORCE_SCRIPT_NAME = "/ming"

# Static and media URLs (must include /ming prefix)
STATIC_URL = "/ming/static/"
MEDIA_URL  = "/ming/media/"

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, "static_collected")
MEDIA_ROOT  = os.path.join(BASE_DIR, "media")

# Cookie name for verified browser session
RESV_SESSION_COOKIE_NAME = "ming_resv_session"

# How long trusted browser stays logged in
RESV_SESSION_DAYS_VALID = 30

# Google Apps Script webhook (you create this URL)
GOOGLE_APPS_SCRIPT_EMAIL_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbyEqtykwvs4Vej2tq6mPQAdc1le6XT6r1JT9UQaaaV8fbkoJPfLrQQ6uwRWNOKya3R0YA/exec"

# Optional: shared secret to prevent abuse
GOOGLE_APPS_SCRIPT_EMAIL_WEBHOOK_SECRET = "change-me"

SECURE_SSL_REDIRECT = False