--
-- PostgreSQL database dump
--

-- Dumped from database version 14.17 (Homebrew)
-- Dumped by pg_dump version 14.17 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO mingdyn;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO mingdyn;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO mingdyn;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO mingdyn;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO mingdyn;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO mingdyn;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_settings_sitesettings; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.core_settings_sitesettings (
    id bigint NOT NULL,
    booking_days_in_advance integer NOT NULL,
    opening_time time without time zone NOT NULL,
    closing_time time without time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT core_settings_sitesettings_booking_days_in_advance_check CHECK ((booking_days_in_advance >= 0))
);


ALTER TABLE public.core_settings_sitesettings OWNER TO mingdyn;

--
-- Name: core_settings_sitesettings_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.core_settings_sitesettings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_settings_sitesettings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO mingdyn;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO mingdyn;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO mingdyn;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO mingdyn;

--
-- Name: locations_location; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.locations_location (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(50) NOT NULL,
    address text NOT NULL,
    phone character varying(50) NOT NULL,
    email character varying(254) NOT NULL,
    opening_hours character varying(200) NOT NULL,
    menu_pdf character varying(200) NOT NULL,
    order_url character varying(200) NOT NULL,
    map_url character varying(200) NOT NULL,
    hero_image character varying(100) NOT NULL
);


ALTER TABLE public.locations_location OWNER TO mingdyn;

--
-- Name: locations_location_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.locations_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menus_menudocument; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.menus_menudocument (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    pdf character varying(100) NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL,
    location_id bigint NOT NULL,
    CONSTRAINT menus_menudocument_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.menus_menudocument OWNER TO mingdyn;

--
-- Name: menus_menudocument_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.menus_menudocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menus_menudocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mingsite_galleryimage; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.mingsite_galleryimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    caption character varying(200) NOT NULL,
    sort_order integer NOT NULL,
    location_id bigint,
    CONSTRAINT mingsite_galleryimage_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.mingsite_galleryimage OWNER TO mingdyn;

--
-- Name: mingsite_galleryimage_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.mingsite_galleryimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mingsite_galleryimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mingsite_location; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.mingsite_location (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(50) NOT NULL,
    address text NOT NULL,
    phone character varying(50) NOT NULL,
    email character varying(254) NOT NULL,
    opening_hours character varying(200) NOT NULL,
    menu_pdf character varying(200) NOT NULL,
    order_url character varying(200) NOT NULL,
    hero_image character varying(100)
);


ALTER TABLE public.mingsite_location OWNER TO mingdyn;

--
-- Name: mingsite_location_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.mingsite_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mingsite_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mingsite_reservationrequest; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.mingsite_reservationrequest (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(80) NOT NULL,
    date timestamp with time zone NOT NULL,
    people integer NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    location_id bigint NOT NULL,
    CONSTRAINT mingsite_reservationrequest_people_check CHECK ((people >= 0))
);


ALTER TABLE public.mingsite_reservationrequest OWNER TO mingdyn;

--
-- Name: mingsite_reservationrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.mingsite_reservationrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mingsite_reservationrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mingsite_testimonial; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.mingsite_testimonial (
    id bigint NOT NULL,
    author character varying(120) NOT NULL,
    text text NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT mingsite_testimonial_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.mingsite_testimonial OWNER TO mingdyn;

--
-- Name: mingsite_testimonial_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.mingsite_testimonial ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mingsite_testimonial_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qrflow_feedback; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.qrflow_feedback (
    id bigint NOT NULL,
    what_went_wrong text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    location_slug character varying(200),
    email character varying(254) NOT NULL
);


ALTER TABLE public.qrflow_feedback OWNER TO mingdyn;

--
-- Name: qrflow_feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.qrflow_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qrflow_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qrflow_location; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.qrflow_location (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(50) NOT NULL,
    place_id character varying(200) NOT NULL
);


ALTER TABLE public.qrflow_location OWNER TO mingdyn;

--
-- Name: qrflow_location_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.qrflow_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qrflow_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_blockeddaymodel; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.reservations_blockeddaymodel (
    id bigint NOT NULL,
    date date NOT NULL,
    reason character varying(200) NOT NULL,
    is_closed boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.reservations_blockeddaymodel OWNER TO mingdyn;

--
-- Name: reservations_blockeddaymodel_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.reservations_blockeddaymodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_blockeddaymodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_dayslotblockmodel; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.reservations_dayslotblockmodel (
    id bigint NOT NULL,
    blocked_seats integer NOT NULL,
    is_closed boolean NOT NULL,
    reason character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    blocked_day_id bigint,
    slot_id bigint NOT NULL,
    CONSTRAINT reservations_dayslotblockmodel_blocked_seats_check CHECK ((blocked_seats >= 0))
);


ALTER TABLE public.reservations_dayslotblockmodel OWNER TO mingdyn;

--
-- Name: reservations_dayslotblockmodel_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.reservations_dayslotblockmodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_dayslotblockmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_emailsessionmodel; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.reservations_emailsessionmodel (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    token_hash character varying(64) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    user_agent character varying(300) NOT NULL,
    ip_prefix character varying(64) NOT NULL,
    is_revoked boolean NOT NULL
);


ALTER TABLE public.reservations_emailsessionmodel OWNER TO mingdyn;

--
-- Name: reservations_emailsessionmodel_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.reservations_emailsessionmodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_emailsessionmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_reservationmodel; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.reservations_reservationmodel (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(40) NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    party_size integer NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    slot_id bigint NOT NULL,
    CONSTRAINT reservations_reservationmodel_party_size_check CHECK ((party_size >= 0))
);


ALTER TABLE public.reservations_reservationmodel OWNER TO mingdyn;

--
-- Name: reservations_reservationmodel_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.reservations_reservationmodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_reservationmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservations_timeslotmodel; Type: TABLE; Schema: public; Owner: mingdyn
--

CREATE TABLE public.reservations_timeslotmodel (
    id bigint NOT NULL,
    slug character varying(50) NOT NULL,
    label character varying(80) NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    capacity integer NOT NULL,
    is_active boolean NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT reservations_timeslotmodel_capacity_check CHECK ((capacity >= 0)),
    CONSTRAINT reservations_timeslotmodel_sort_order_check CHECK ((sort_order >= 0))
);


ALTER TABLE public.reservations_timeslotmodel OWNER TO mingdyn;

--
-- Name: reservations_timeslotmodel_id_seq; Type: SEQUENCE; Schema: public; Owner: mingdyn
--

ALTER TABLE public.reservations_timeslotmodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservations_timeslotmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_settings_sitesettings core_settings_sitesettings_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.core_settings_sitesettings
    ADD CONSTRAINT core_settings_sitesettings_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: locations_location locations_location_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.locations_location
    ADD CONSTRAINT locations_location_pkey PRIMARY KEY (id);


--
-- Name: locations_location locations_location_slug_key; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.locations_location
    ADD CONSTRAINT locations_location_slug_key UNIQUE (slug);


--
-- Name: menus_menudocument menus_menudocument_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.menus_menudocument
    ADD CONSTRAINT menus_menudocument_pkey PRIMARY KEY (id);


--
-- Name: mingsite_galleryimage mingsite_galleryimage_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.mingsite_galleryimage
    ADD CONSTRAINT mingsite_galleryimage_pkey PRIMARY KEY (id);


--
-- Name: mingsite_location mingsite_location_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.mingsite_location
    ADD CONSTRAINT mingsite_location_pkey PRIMARY KEY (id);


--
-- Name: mingsite_location mingsite_location_slug_key; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.mingsite_location
    ADD CONSTRAINT mingsite_location_slug_key UNIQUE (slug);


--
-- Name: mingsite_reservationrequest mingsite_reservationrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.mingsite_reservationrequest
    ADD CONSTRAINT mingsite_reservationrequest_pkey PRIMARY KEY (id);


--
-- Name: mingsite_testimonial mingsite_testimonial_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.mingsite_testimonial
    ADD CONSTRAINT mingsite_testimonial_pkey PRIMARY KEY (id);


--
-- Name: qrflow_feedback qrflow_feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.qrflow_feedback
    ADD CONSTRAINT qrflow_feedback_pkey PRIMARY KEY (id);


--
-- Name: qrflow_location qrflow_location_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.qrflow_location
    ADD CONSTRAINT qrflow_location_pkey PRIMARY KEY (id);


--
-- Name: qrflow_location qrflow_location_slug_key; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.qrflow_location
    ADD CONSTRAINT qrflow_location_slug_key UNIQUE (slug);


--
-- Name: reservations_blockeddaymodel reservations_blockeddaymodel_date_key; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_blockeddaymodel
    ADD CONSTRAINT reservations_blockeddaymodel_date_key UNIQUE (date);


--
-- Name: reservations_blockeddaymodel reservations_blockeddaymodel_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_blockeddaymodel
    ADD CONSTRAINT reservations_blockeddaymodel_pkey PRIMARY KEY (id);


--
-- Name: reservations_dayslotblockmodel reservations_dayslotbloc_blocked_day_id_slot_id_9d1be77f_uniq; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_dayslotblockmodel
    ADD CONSTRAINT reservations_dayslotbloc_blocked_day_id_slot_id_9d1be77f_uniq UNIQUE (blocked_day_id, slot_id);


--
-- Name: reservations_dayslotblockmodel reservations_dayslotblockmodel_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_dayslotblockmodel
    ADD CONSTRAINT reservations_dayslotblockmodel_pkey PRIMARY KEY (id);


--
-- Name: reservations_emailsessionmodel reservations_emailsessionmodel_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_emailsessionmodel
    ADD CONSTRAINT reservations_emailsessionmodel_pkey PRIMARY KEY (id);


--
-- Name: reservations_emailsessionmodel reservations_emailsessionmodel_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_emailsessionmodel
    ADD CONSTRAINT reservations_emailsessionmodel_token_hash_key UNIQUE (token_hash);


--
-- Name: reservations_reservationmodel reservations_reservationmodel_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_reservationmodel
    ADD CONSTRAINT reservations_reservationmodel_pkey PRIMARY KEY (id);


--
-- Name: reservations_timeslotmodel reservations_timeslotmodel_pkey; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_timeslotmodel
    ADD CONSTRAINT reservations_timeslotmodel_pkey PRIMARY KEY (id);


--
-- Name: reservations_timeslotmodel reservations_timeslotmodel_slug_key; Type: CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_timeslotmodel
    ADD CONSTRAINT reservations_timeslotmodel_slug_key UNIQUE (slug);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: locations_location_slug_0338bba7_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX locations_location_slug_0338bba7_like ON public.locations_location USING btree (slug varchar_pattern_ops);


--
-- Name: menus_menudocument_location_id_1e24b02c; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX menus_menudocument_location_id_1e24b02c ON public.menus_menudocument USING btree (location_id);


--
-- Name: mingsite_galleryimage_location_id_217213e6; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX mingsite_galleryimage_location_id_217213e6 ON public.mingsite_galleryimage USING btree (location_id);


--
-- Name: mingsite_location_slug_e1ba61e7_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX mingsite_location_slug_e1ba61e7_like ON public.mingsite_location USING btree (slug varchar_pattern_ops);


--
-- Name: mingsite_reservationrequest_location_id_a74f1257; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX mingsite_reservationrequest_location_id_a74f1257 ON public.mingsite_reservationrequest USING btree (location_id);


--
-- Name: qrflow_location_slug_cddbca2d_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX qrflow_location_slug_cddbca2d_like ON public.qrflow_location USING btree (slug varchar_pattern_ops);


--
-- Name: reservation_date_2d52ec_idx; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservation_date_2d52ec_idx ON public.reservations_reservationmodel USING btree (date, "time");


--
-- Name: reservation_date_980a9a_idx; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservation_date_980a9a_idx ON public.reservations_reservationmodel USING btree (date, slot_id);


--
-- Name: reservation_email_3021a2_idx; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservation_email_3021a2_idx ON public.reservations_reservationmodel USING btree (email, phone);


--
-- Name: reservations_dayslotblockmodel_blocked_day_id_70182769; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservations_dayslotblockmodel_blocked_day_id_70182769 ON public.reservations_dayslotblockmodel USING btree (blocked_day_id);


--
-- Name: reservations_dayslotblockmodel_slot_id_6d9d76da; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservations_dayslotblockmodel_slot_id_6d9d76da ON public.reservations_dayslotblockmodel USING btree (slot_id);


--
-- Name: reservations_emailsessionmodel_email_272c0d04; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservations_emailsessionmodel_email_272c0d04 ON public.reservations_emailsessionmodel USING btree (email);


--
-- Name: reservations_emailsessionmodel_email_272c0d04_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservations_emailsessionmodel_email_272c0d04_like ON public.reservations_emailsessionmodel USING btree (email varchar_pattern_ops);


--
-- Name: reservations_emailsessionmodel_expires_at_1e61e8d0; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservations_emailsessionmodel_expires_at_1e61e8d0 ON public.reservations_emailsessionmodel USING btree (expires_at);


--
-- Name: reservations_emailsessionmodel_token_hash_6779a14e_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservations_emailsessionmodel_token_hash_6779a14e_like ON public.reservations_emailsessionmodel USING btree (token_hash varchar_pattern_ops);


--
-- Name: reservations_reservationmodel_slot_id_b5267e75; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservations_reservationmodel_slot_id_b5267e75 ON public.reservations_reservationmodel USING btree (slot_id);


--
-- Name: reservations_timeslotmodel_slug_72eb8ea3_like; Type: INDEX; Schema: public; Owner: mingdyn
--

CREATE INDEX reservations_timeslotmodel_slug_72eb8ea3_like ON public.reservations_timeslotmodel USING btree (slug varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: menus_menudocument menus_menudocument_location_id_1e24b02c_fk_locations; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.menus_menudocument
    ADD CONSTRAINT menus_menudocument_location_id_1e24b02c_fk_locations FOREIGN KEY (location_id) REFERENCES public.locations_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mingsite_galleryimage mingsite_galleryimag_location_id_217213e6_fk_mingsite_; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.mingsite_galleryimage
    ADD CONSTRAINT mingsite_galleryimag_location_id_217213e6_fk_mingsite_ FOREIGN KEY (location_id) REFERENCES public.mingsite_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mingsite_reservationrequest mingsite_reservation_location_id_a74f1257_fk_mingsite_; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.mingsite_reservationrequest
    ADD CONSTRAINT mingsite_reservation_location_id_a74f1257_fk_mingsite_ FOREIGN KEY (location_id) REFERENCES public.mingsite_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_dayslotblockmodel reservations_dayslot_blocked_day_id_70182769_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_dayslotblockmodel
    ADD CONSTRAINT reservations_dayslot_blocked_day_id_70182769_fk_reservati FOREIGN KEY (blocked_day_id) REFERENCES public.reservations_blockeddaymodel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_dayslotblockmodel reservations_dayslot_slot_id_6d9d76da_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_dayslotblockmodel
    ADD CONSTRAINT reservations_dayslot_slot_id_6d9d76da_fk_reservati FOREIGN KEY (slot_id) REFERENCES public.reservations_timeslotmodel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservations_reservationmodel reservations_reserva_slot_id_b5267e75_fk_reservati; Type: FK CONSTRAINT; Schema: public; Owner: mingdyn
--

ALTER TABLE ONLY public.reservations_reservationmodel
    ADD CONSTRAINT reservations_reserva_slot_id_b5267e75_fk_reservati FOREIGN KEY (slot_id) REFERENCES public.reservations_timeslotmodel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

