# Generated by Django 5.2.7 on 2026-02-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='location',
        ),
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='location_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='prize_code',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
