# Generated by Django 5.2.7 on 2026-02-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrflow', '0002_remove_feedback_location_feedback_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='what_went_wrong',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='prize_code',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='visit_date',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
