# Generated by Django 5.2.7 on 2026-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_days_in_advance', models.PositiveIntegerField(default=3)),
                ('opening_time', models.TimeField(default='12:00', help_text='Earliest reservable time.')),
                ('closing_time', models.TimeField(default='22:00', help_text='Latest reservable time.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
