# Generated by Django 5.2.7 on 2026-02-24 10:48

import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='time',
            field=models.TimeField(default=reservations.models.default_time),
        ),
    ]
