# Generated by Django 5.2.7 on 2026-04-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservationmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='arrival_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='is_arrived',
            field=models.BooleanField(default=False),
        ),
    ]
