# Generated by Django 5.2.7 on 2026-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservationmodel_arrival_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='cancellation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservationmodel',
            index=models.Index(fields=['email', 'status'], name='reservation_email_e95577_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationmodel',
            index=models.Index(fields=['status', 'date', 'time'], name='reservation_status_d04beb_idx'),
        ),
    ]
