# Generated by Django 5.2.7 on 2025-10-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('menu_pdf', models.URLField(blank=True)),
                ('order_url', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='locations/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
